### ISSUE TITLE
Can't run `seashell` on Windows

### ISSUE THREAD

**Issue by korboybeats** [EntySec/SeaShell#21]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\korbo\AppData\Local\Programs\Python\Python312\Scripts\seashell.exe\__main__.py", line 4, in <module>
  File "C:\Users\korbo\AppData\Local\Programs\Python\Python312\Lib\site-packages\seashell\__init__.py", line 30, in <module>
    from seashell.core.console import Console
  File "C:\Users\korbo\AppData\Local\Programs\Python\Python312\Lib\site-packages\seashell\core\console.py", line 32, in <module>
    from hatsploit.lib.commands import Commands
  File "C:\Users\korbo\AppData\Local\Programs\Python\Python312\Lib\site-packages\hatsploit\__init__.py", line 30, in <module>
    from .__main__ import HatSploit, HatSploitGen
  File "C:\Users\korbo\AppData\Local\Programs\Python\Python312\Lib\site-packages\hatsploit\__main__.py", line 30, in <module>
    from hatasm import HatAsm
  File "C:\Users\korbo\AppData\Local\Programs\Python\Python312\Lib\site-packages\hatasm\__init__.py", line 25, in <module>
    from .__main__ import HatAsm
  File "C:\Users\korbo\AppData\Local\Programs\Python\Python312\Lib\site-packages\hatasm\__main__.py", line 25, in <module>
    from .assembler import Assembler
  File "C:\Users\korbo\AppData\Local\Programs\Python\Python312\Lib\site-packages\hatasm\assembler.py", line 27, in <module>
    import readline
  File "C:\Users\korbo\AppData\Local\Programs\Python\Python312\Lib\site-packages\readline.py", line 34, in <module>
    rl = Readline()
         ^^^^^^^^^^
  File "C:\Users\korbo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "C:\Users\korbo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "C:\Users\korbo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "C:\Users\korbo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
           ^^^^^^^^^^^^^^
  File "C:\Users\korbo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'

**Comment by enty8080** [comment]
SeaShell is not supported on Windows
