### ISSUE TITLE
facing a issue with seashell installation for Mac 

### ISSUE THREAD

**Issue by Abdullah112006** [EntySec/SeaShell#24]
when I am trying toi install seashell with command that provided in readme file its give me this error:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
googletrans-py 4.0.0 requires h2<5,>=4, but you have h2 3.2.0 which is incompatible.
googletrans-py 4.0.0 requires httpx>=0.22.0, but you have httpx 0.13.3 which is incompatible.
seleniumbase 4.19.2 requires chardet==5.2.0, but you have chardet 3.0.4 which is incompatible.
seleniumbase 4.19.2 requires charset-normalizer==3.3.0, but you have charset-normalizer 3.3.2 which is incompatible.
seleniumbase 4.19.2 requires h11==0.14.0, but you have h11 0.9.0 which is incompatible.
seleniumbase 4.19.2 requires idna==3.4, but you have idna 2.10 which is incompatible.
seleniumbase 4.19.2 requires urllib3<2.1.0,>=1.26.16; python_version >= "3.10", but you have urllib3 2.2.1 which is incompatible.
google-api-core 2.11.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5, but you have protobuf 5.26.0 which is incompatible.
google-cloud-translate 3.12.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 5.26.0 which is incompatible.

**Comment by Abdullah112006** [comment]
its give me this error:
Traceback (most recent call last):
  File "/Users/dnn/PycharmProjects/pythonProject/.venv/bin/seashell", line 5, in <module>
    from seashell import cli
  File "/Users/dnn/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/seashell/__init__.py", line 30, in <module>
    from seashell.core.console import Console
  File "/Users/dnn/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/seashell/core/console.py", line 32, in <module>
    from hatsploit.lib.commands import Commands
  File "/Users/dnn/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/hatsploit/__init__.py", line 30, in <module>
    from .__main__ import HatSploit, HatSploitGen
  File "/Users/dnn/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/hatsploit/__main__.py", line 30, in <module>
    from hatasm import HatAsm
  File "/Users/dnn/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/hatasm/__init__.py", line 25, in <module>
    from .__main__ import HatAsm
  File "/Users/dnn/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/hatasm/__main__.py", line 25, in <module>
    from .assembler import Assembler
  File "/Users/dnn/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/hatasm/assembler.py", line 25, in <module>
    import keystone
  File "/Users/dnn/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/keystone/__init__.py", line 4, in <module>
    from .keystone import Ks, ks_version, ks_arch_supported, version_bind, debug, KsError, __version__
  File "/Users/dnn/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/keystone/keystone.py", line 74, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.

**Comment by enty8080** [comment]
@Abdullah112006 Please read previous issues related to your problem. I suggest you check on solution from #14

**Comment by Abdullah112006** [comment]
still not working, I checked #14

**Comment by Abdullah112006** [comment]
Traceback (most recent call last):
  File "/Users/dnn/PycharmProjects/pythonProject/.venv/bin/seashell", line 5, in <module>
    from seashell import cli
  File "/Users/dnn/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/seashell/__init__.py", line 28, in <module>
    from seashell.core.ipa import IPA
  File "/Users/dnn/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/seashell/core/ipa.py", line 31, in <module>
    from pex.string import String
ModuleNotFoundError: No module named 'pex.string'
