### ISSUE TITLE
Issue with installation on Mac 

### ISSUE THREAD

**Issue by Abdullah112006** [EntySec/SeaShell#25]
Traceback (most recent call last):
  File "/Users/dnn/PycharmProjects/pythonProject/.venv/bin/seashell", line 5, in <module>
    from seashell import cli
  File "/Users/dnn/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/seashell/__init__.py", line 28, in <module>
    from seashell.core.ipa import IPA
  File "/Users/dnn/PycharmProjects/pythonProject/.venv/lib/python3.11/site-packages/seashell/core/ipa.py", line 31, in <module>
    from pex.string import String
ModuleNotFoundError: No module named 'pex.string'

**Comment by enty8080** [comment]
@Abdullah112006 Stop opening multiple same issues. How did you install SeaShell? Try to install it outside venv.

**Comment by Abdullah112006** [comment]
sorry, its give me this error when I use seashell command in outside venv: zsh: command not found: seashell
