### ISSUE TITLE
Install .ipa without TrollStore

### ISSUE THREAD

**Issue by fuad00** [EntySec/SeaShell#6]
TrollSotre is just an ipa installer witch uses CoreTrust bug. Why can't we include CoreTrust itself into generated ipa?

**Comment by kenzWeb** [comment]
я получаю вот такую ошибку при вводе команды seashell:File "/Library/Frameworks/Python.framework/Versions/3.12/bin/seashell", line 5, in <module>
    from seashell import cli
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/seashell/__init__.py", line 31, in <module>
    from seashell.core.console import Console
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/seashell/core/console.py", line 32, in <module>
    from hatsploit.lib.commands import Commands
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/hatsploit/__init__.py", line 30, in <module>
    from .__main__ import HatSploit, HatSploitGen
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/hatsploit/__main__.py", line 30, in <module>
    from hatasm import HatAsm
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/hatasm/__init__.py", line 25, in <module>
    from .__main__ import HatAsm
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/hatasm/__main__.py", line 26, in <module>
    from .disassembler import Disassembler
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/hatasm/disassembler.py", line 25, in <module>
    import capstone
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/capstone/__init__.py", line 425, in <module>
    _cs = _load_lib(_path)
          ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/capstone/__init__.py", line 398, in _load_lib
    return ctypes.cdll.LoadLibrary(lib_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/capstone/lib/libcapstone.dylib, 0x0006): tried: '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/capstone/lib/libcapstone.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/capstone/lib/libcapstone.dylib' (no such file), '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/capstone/lib/libcapstone.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by enty8080** [comment]
@kenzWeb If you are on macOS then there is the same issue here - https://github.com/keystone-engine/keystone/issues/386

**Comment by enty8080** [comment]
@fuad00 Because TrollStore bypasses the signature check that `installd` usually does. Read more about this here - https://github.com/opa334/ChOma/issues/6

**Comment by kenzWeb** [comment]
> @kenzWebЕсли вы используете macOS, то здесь та же проблема — [keystone-engine/keystone#386.](https://github.com/keystone-engine/keystone/issues/386)

It worked, but now there's another error(i have mac m1)

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/seashell", line 5, in <module>
    from seashell import cli
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/seashell/__init__.py", line 31, in <module>
    from seashell.core.console import Console
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/seashell/core/console.py", line 32, in <module>
    from hatsploit.lib.commands import Commands
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/hatsploit/__init__.py", line 30, in <module>
    from .__main__ import HatSploit, HatSploitGen
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/hatsploit/__main__.py", line 30, in <module>
    from hatasm import HatAsm
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/hatasm/__init__.py", line 25, in <module>
    from .__main__ import HatAsm
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/hatasm/__main__.py", line 26, in <module>
    from .disassembler import Disassembler
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/hatasm/disassembler.py", line 25, in <module>
    import capstone
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/capstone/__init__.py", line 425, in <module>
    _cs = _load_lib(_path)
          ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/capstone/__init__.py", line 398, in _load_lib
    return ctypes.cdll.LoadLibrary(lib_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/capstone/lib/libcapstone.dylib, 0x0006): tried: '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/capstone/lib/libcapstone.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/capstone/lib/libcapstone.dylib' (no such file), '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/capstone/lib/libcapstone.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by enty8080** [comment]
@kenzWeb  Try this command

```
pip3 install --user -U --no-cache-dir --force-reinstall --no-binary capstone capstone
```

**Comment by kenzWeb** [comment]
> @kenzWeb Try this command
> 
> ```
> pip3 install --user -U --no-cache-dir --force-reinstall --no-binary capstone capstone
> ```

thanks bro, its worked

**Comment by kenzWeb** [comment]
> @kenzWeb Try this command
> 
> ```
> pip3 install --user -U --no-cache-dir --force-reinstall --no-binary capstone capstone
> ```
> 
> I am on M1 too and this is the only solution that worked for me.

I'm probably boring with my questions, but now I can't start TCP server(Failed to start TCP listener on port 5169!)

**Comment by enty8080** [comment]
@kenzWeb Are you sure that this port is not in use? Can you please try and change port number and check if it works?

**Comment by kenzWeb** [comment]
> @kenzWebВы уверены, что этот порт не используется? Можете ли вы попробовать изменить номер порта и проверить, работает ли он?

<img width="610" alt="Снимок экрана 2024-01-11 в 22 20 37" src="https://github.com/EntySec/SeaShell/assets/77916046/9a125877-4f00-4040-af33-e336205013f5">
I checked, the port's not busy

**Comment by enty8080** [comment]
@kenzWeb Hmm, this port works for me. Can you please check if your IP is `192.168.5.10`. For this, run `ifconfig` and search for `en0`. Or you can open Preferences -> Network and look for your local IP.

**Comment by kenzWeb** [comment]
> @kenzWeb Hmm, this port works for me. Can you please check if your IP is `192.168.5.10`. For this, run `ifconfig` and search for `en0`. Or you can open Preferences -> Network and look for your local IP.

The interesting thing is that when I enter 0.0.0.0.0 5679, the server works

**Comment by enty8080** [comment]
@kenzWeb Thats because `192.168.5.10` is invalid. `0.0.0.0` means it started listener on all network interfaces.

**Comment by kenzWeb** [comment]
> @kenzWebЭто потому, что `192.168.5.10`это недействительно. `0.0.0.0`означает, что он запустил прослушиватель на всех сетевых интерфейсах.

Now it's telling me that the listener command doesn't exist.

<img width="388" alt="Снимок экрана 2024-01-11 в 22 50 00" src="https://github.com/EntySec/SeaShell/assets/77916046/8f6cd5a4-2010-447d-a2cf-44da0137486c">

**Comment by enty8080** [comment]
@kenzWeb This can be fixed if you reinstall SeaShell. However I don't know why this error appears, since you have already used this command.

**Comment by kenzWeb** [comment]
> ```
> pip3 install --user -U --no-cache-dir --force-reinstall --no-binary capstone capstone
> ```

When I install pwny the way you did, I'm missing this command

**Comment by kenzWeb** [comment]
> @kenzWeb This can be fixed if you reinstall SeaShell. However I don't know why this error appears, since you have already used this command.

If I don't install, I get an error when I log into the application :(seashell)> Exception in Thread-1 (handle_device):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/seashell/commands/listener.py", line 47, in handle_device
    device = self.handler.handle()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/seashell/core/device.py", line 131, in handle
    session.open(self.client, loader=False)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pwny/session.py", line 87, in open
    client = self.ssl.wrap_client(client)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pex/ssl/openssl.py", line 76, in wrap_client
    return ssl.wrap_socket(
           ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'

**Comment by enty8080** [comment]
@kenzWeb Okay, write these commands one by one in your terminal:

```
pip3 install --force-reinstall git+https://github.com/EntySec/SeaShell
pip3 install --user -U --no-cache-dir --force-reinstall --no-binary keystone-engine keystone-engine
pip3 install --user -U --no-cache-dir --force-reinstall --no-binary capstone capstone
```

**Comment by kenzWeb** [comment]
> ^^^^^^^^^^^^^^^^^^
> File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/seashell/core/device.py", line 131, in handle
> session.open(self.client, loader=False)
> File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pwny/session.py", line 87, in open
> client = self.ssl.wrap_client(client)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pex/ssl/openssl.py", line 76, in wrap_client
> return ssl.wrap_socket(
> ^^^^^^^^^^^^^^^
> AttributeError: module 'ssl' has no attribute 'wrap_socket'

I've already entered it, but I get an error when I go into the app.

**Comment by enty8080** [comment]
@kenzWeb What is your python version?

**Comment by kenzWeb** [comment]
> @kenzWeb What is your python version?

last

**Comment by enty8080** [comment]
@kenzWeb Gotcha. I found a problem. I will let you know when I fix it

**Comment by kenzWeb** [comment]
> Gotcha. I found a problem. I will let you know when I fix it

Okay, thank you very much

**Comment by enty8080** [comment]
I fixed the problem, can you please type these commands:

```
pip3 uninstall pex
pip3 install git+https://github.com/entysec/pex
```

And then try to use SeaShell.

**Comment by kenzWeb** [comment]
> @kenzWeb Я исправил проблему, не могли бы вы ввести следующие команды:
> 
> ```
> pip3 uninstall pex
> pip3 install git+https://github.com/entysec/pex
> ```
> 
> А затем попробуйте использовать SeaShell.

It works, thank you.

**Comment by enty8080** [comment]
@kenzWeb Have you tired accessing the phone remotely?

**Comment by kenzWeb** [comment]
> @kenzWeb Have you tired accessing the phone remotely?

Yeah, I got access to my cell phone

**Comment by fuad00** [comment]
> bypasses the signature check

let's bypass that signature check in our ipa payloads?
